behaviors:
  Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    #  gail:
    #    strength: 0.5
    #    gamma: 0.9
    #    demo_path: Assets/Demonstrations/YourDemoName.demo
    #    encoding_size: 64
    #    use_actions: true
    time_horizon: 64
    max_steps: 10000000
    summary_freq: 50000